{
    "name": "Accounting Reports : Addis Systems",
    "version": "17.0.1.0",
    "sequence": 51,
    "summary": "Addis Systems Accounting Basic Reports",
    "description": """
        This Module is developed by Addis Systems for Basic Accounting Reports.
            ========================================
    """,
    "category": "Addis Systems/Accounting",
    "author": "Addis Systems/Beruk W.",
    "website": "https://www.addissystems.et/",
    "license": "LGPL-3",
    "depends": ["addis_systems_accounting_base", "addis_systems_accounting", "report_xlsx","accounting_pdf_reports","om_account_daily_reports"],
    "external_dependencies": {"python": ["pulsar-client", "avro", "avro-schema"]},
    "data": [
        "security/ir.model.access.csv",
        "reports/AddisSystemsGeneralLedgerReportInherit.xml",
        "reports/accounting_period.xml",
        "reports/accounting_period_report_template.xml",
        "wizards/addisystems_account_balance_budget_report.xml",
        "wizards/addisystems_glaccount_summary_report.xml",
        "wizards/addisystems_account_cash_statement_report.xml",
        "wizards/addisystems_account_income_statement_report.xml",
        "wizards/addisystems_account_reconcillation_report.xml",
        "reports/addisystems_account_balance_budget_report.xml",
        "reports/addisystems_account_cash_flow_report.xml",
        "reports/addisystems_gl_account_summary_report.xml",
        "reports/addisystems_account_cash_flow_report.xml",
        "reports/addisystems_account_income_statement_report.xml",
        "reports/addisystems_account_income_12_statement_report_twelve_period.xml",
        "reports/addisystems_account_reconcillation_report.xml",
        "reports/reports.xml"
    ],
    "assets": {
        "web._assets_primary_variables": [],
        "web._assets_backend_helpers": [],
        "web.assets_backend": [],
        "web.assets_frontend": [],
        "web.assets_tests": [],
        "web.qunit_suite_tests": [],
        "web.assets_qweb": [],
    },
    "demo": [],
    "installable": True,
    "price": 49.99,
    "currency": "ETB",
    "application": True,
    'auto_install': ["addis_systems_accounting_base", "addis_systems_accounting"],
}
