{
    "name": "Addis Systems Manufacturing",
    "version": "17.0.1.0",
    "sequence": 52,
    "summary": "Addis Systems Manufacturing Basic Configurations and Modifications",
    "description": """
        This Module is developed by Addis Systems for Basic Manufacturing Configurations and Modifications.
            ========================================
    """,
    "category": "Addis Systems/Manufacturing",
    "author": "Addis Systems/Beruk W.",
    "website": "https://www.addissystems.et/",
    "license": "LGPL-3",
    "depends": ["addis_systems_manufacturing_base","mrp"],
    "external_dependencies": {"python": ["pulsar-client", "avro", "avro-schema"]},
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/stock_request_picking_type.xml",
        "views/AddisSystemsManufacturingProductionInheritedViews.xml",
        "reports/AddisSystemsManufacturingProductionReportInherited.xml",
        "views/mrp_production_views.xml",
        "views/document_activity.xml",
        "views/product_request_views.xml",
        "views/viewstockpicking.xml",
        "views/stock_picking_views.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [],
        "web._assets_backend_helpers": [],
        "web.assets_backend": [],
        "web.assets_frontend": [],
        "web.assets_tests": [],
        "web.qunit_suite_tests": [],
        "web.assets_qweb": [],
    },
    "demo": [],
    "installable": True,
    "price": 49.99,
    "currency": "ETB",
    "application": True,
    'auto_install': False,
}
